### ISSUE TITLE
Progression to Next Node - Error

### ISSUE THREAD

**Issue by scottsou145** [tairea/galaxy-maps-v2#80]
If the last mission has no submission event they cannot go onto the next node. I don't know if there is a place to click or what. I had to create a task with a submission in order to get them to the next node.

**Comment by tairea** [comment]
Comments from Stefan over on messenger

So there's a few of things going on here.

1) For all the topics in the BEATS GALAXY course, there are no prerequisites set up. I checked a couple of other courses and noticed that they have prerequisites set up for all the topics.

2) In the MissionCompletedDialog, during the unlockNextTopics function, the query to get next topics filters where the topics have the current topic as a prerequisite e.g. .where("prerequisites", "array-contains", this.currentTopic.id)

3) In the MissionCompletedDialog, during the unlockNextTopics function, the logic checks to see if any of the fetched next topics have any prerequisites and if so loops through each one to check that the prerequisite is met. If there are no prerequisites then the fetched next topic is simply unlocked (though this case will never happen because of point 2 above).

4) In the SubmissionReviewDialog, during the unlockNextTopics function, the query to get query to get next topics filters where the topics have the current topic as a prerequisite e.g. .where("prerequisites", "array-contains", this.submission.contextTopic.id)

5) In the SubmissionReviewDialog, during the unlockNextTopics function, the logic is different to what is in the MissionCompletedDialog. It simply unlocks the fetched next topics without doing any further checks.

So here's the clarifications required.

a) is it valid for a non-introduction topic to have no prerequisites?

b) if it is valid, how are these non-introduction topics unlocked? 

c) is SubmissionReviewDialog supposed to do prerequisite checks similar to MissionCompletedDialog?

**Comment by tairea** [comment]
a) is it valid for a non-introduction topic to have no prerequisites? **_YES. These nodes should always be unlocked._**

b) if it is valid, how are these non-introduction topics unlocked? **_They should be unlocked from the start_**

c) is SubmissionReviewDialog supposed to do prerequisite checks similar to MissionCompletedDialog? _**I dont think so**_
